"""
backend/explanation/providers/demo_provider.py - Demo Provider.

Streams deterministic template responses when API keys are not available.
Guarantees Athena remains fully runnable in a sandbox environment.
"""

import time
from collections.abc import Generator

from backend.explanation.prompt_builder import PromptPackage
from backend.explanation.providers.base import ExplanationProvider, GenerationResponse


class DemoProvider(ExplanationProvider):
    """
    Mock provider for demonstrations without API keys.
    """

    def __init__(self, model_name: str = "athena-demo-model", temperature: float = 0.0):
        super().__init__(model_name, temperature)

    def is_available(self) -> bool:
        return True

    def _generate_demo_text(self, prompt: PromptPackage) -> str:
        ctx_type = prompt.metadata.get("context_type", "unknown")

        # A simple deterministic response
        response = "Based on the verified evidence provided, here is my analysis:\n\n"

        if ctx_type == "player":
            response += "This player profile demonstrates elite capabilities, particularly aligned with their role classification. The metrics provided in the context directly support the decision signals attached to this profile. Specifically, their attacking output is supported by strong underlying expected goals.\n\n"
        elif ctx_type == "team":
            response += "The team's aggregated capability profile suggests a clear tactical identity. Their squad size and average age indicate a balanced roster construction. The evidence confirms their primary playing style.\n\n"
        elif ctx_type == "recruitment":
            response += "Reviewing the recruitment context, the top candidates strongly match the required positional and tactical criteria. The fit scores reflect their alignment with your requested capabilities. The primary trade-offs have been identified.\n\n"
        else:
            response += "I have reviewed the provided context and verified the data structure.\n\n"

        response += "*Note: This is a deterministic response generated by the DemoProvider because no API keys were configured for the external LLM services.*"

        return response

    def stream(
        self, prompt: PromptPackage
    ) -> Generator[GenerationResponse, None, None]:
        text = self._generate_demo_text(prompt)
        # Yield word by word to simulate streaming
        words = text.split(" ")
        for word in words:
            yield GenerationResponse(
                generated_text=word + " ", provider="demo", model=self.model_name
            )
            time.sleep(0.05)  # Simulate network latency

    def generate(self, prompt: PromptPackage) -> GenerationResponse:
        return GenerationResponse(
            generated_text=self._generate_demo_text(prompt),
            provider="demo",
            model=self.model_name,
            finish_reason="stop",
        )
